import io
import re
from typing import Any, Dict, List

import openpyxl
import pdfplumber
import streamlit as st
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

# ─── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Bank Statement → Excel",
    page_icon="🏦",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ─── Styles ───────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    /* Hide default Streamlit chrome */
    #MainMenu, footer { visibility: hidden; }
    .block-container { padding-top: 2rem; padding-bottom: 2rem; }

    /* Header */
    .app-header {
        background: #0F1F35;
        border-bottom: 3px solid #63B3ED;
        padding: 1.1rem 1.5rem;
        border-radius: 10px;
        margin-bottom: 1.5rem;
        display: flex;
        align-items: center;
        gap: 1rem;
    }
    .app-header h1 {
        color: #FFFFFF;
        font-size: 1.4rem;
        margin: 0;
        font-weight: 700;
    }
    .app-header p {
        color: #94A3B8;
        font-size: 0.8rem;
        margin: 0;
        font-family: monospace;
    }

    /* Stat cards */
    .stat-row { display: flex; gap: 1rem; margin-bottom: 1.5rem; flex-wrap: wrap; }
    .stat-card {
        background: #FFFFFF;
        border: 1px solid #CBD5E1;
        border-radius: 10px;
        padding: 1rem 1.5rem;
        flex: 1;
        min-width: 160px;
        box-shadow: 0 1px 3px rgba(0,0,0,0.06);
    }
    .stat-label { font-size: 0.75rem; color: #64748B; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; }
    .stat-value { font-size: 1.5rem; font-weight: 700; color: #0F1F35; margin-top: 0.2rem; }
    .stat-sub   { font-size: 0.75rem; color: #94A3B8; font-family: monospace; }

    /* Info grid */
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0; border: 1px solid #CBD5E1; border-radius: 8px; overflow: hidden; }
    .info-row  { display: contents; }
    .info-label-cell { background: #F8FAFC; padding: 0.55rem 0.9rem; font-size: 0.85rem; font-weight: 600; color: #0F1F35; border-bottom: 1px solid #E2E8F0; }
    .info-value-cell { background: #FFFFFF;  padding: 0.55rem 0.9rem; font-size: 0.85rem; color: #334155; border-bottom: 1px solid #E2E8F0; font-family: monospace; }

    /* Prompt box */
    .prompt-box {
        background: #0F1F35;
        border-radius: 10px;
        padding: 1.25rem;
        color: #94A3B8;
        font-family: monospace;
        font-size: 0.78rem;
        white-space: pre-wrap;
        word-break: break-word;
        max-height: 300px;
        overflow-y: auto;
        border: 1px solid #2B5282;
    }

    /* Success / warning banners */
    .success-pill {
        display: inline-flex; align-items: center; gap: 0.4rem;
        background: #F0FFF4; border: 1px solid #9AE6B4;
        color: #276749; border-radius: 20px; padding: 0.3rem 0.9rem;
        font-size: 0.8rem; font-weight: 600; margin-bottom: 1rem;
    }
    .warn-pill {
        display: inline-flex; align-items: center; gap: 0.4rem;
        background: #FFFBEB; border: 1px solid #F6E05E;
        color: #744210; border-radius: 20px; padding: 0.3rem 0.9rem;
        font-size: 0.8rem; font-weight: 600; margin-bottom: 1rem;
    }
</style>
""", unsafe_allow_html=True)

# ─── Extraction logic (ported from main.py, deterministic only) ───────────────

AI_EXCEL_PROMPT_TEMPLATE = """You are an expert bank statement data extraction assistant.

Create a clean Excel-ready output from the PDF text below.

Requirements:
- Preserve every transaction row in the statement.
- Create two sheets: Account Details and Transactions.
- Account Details columns: Field, Value.
- Transactions columns: Date, Particulars, Withdrawal, Deposit, Balance.
- Keep amounts exactly as written unless a clear formatting cleanup is needed.
- Put withdrawals and deposits in separate columns. Leave missing values blank.
- If a transaction description wraps across lines, merge it into the same row.
- Ignore page headers, footers, disclaimers, duplicate column headings, and summary noise.
- Return the result as CSV blocks, one block per sheet, so I can paste/import it into Excel.
- If anything is uncertain, add a short Notes section after the CSV blocks.

PDF text:
{pdf_text}
"""

DATE_RE   = re.compile(r'^(\d{2}-(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-\d{4})', re.IGNORECASE)
NUMBER_RE = re.compile(r'^[\d,]+(?:\.\d+)?$')

DISCLAIMER_MARKERS = [
    'this is an auto generated e-statement',
    'this is auto generated',
    'for any query',
    'if you need any clarification',
    'please contact your branch',
    'please contact the branch',
    'generated by',
    'statement generated',
    'disclaimer',
]


def is_disclaimer_text(text: str) -> bool:
    if not text:
        return False
    normalized = re.sub(r'\s+', ' ', text).strip().lower()
    return any(m in normalized for m in DISCLAIMER_MARKERS)


def starts_new_transaction_row(line_words: list[dict]) -> bool:
    if not line_words:
        return False
    return bool(DATE_RE.match(line_words[0].get('text', '').strip()))


def words_to_lines(page, y_tolerance: int = 6) -> list[list[dict]]:
    words = page.extract_words(x_tolerance=4, y_tolerance=4)
    if not words:
        return []
    words.sort(key=lambda w: (w['top'] + w['bottom']) / 2)
    lines, current_line, current_y = [], [], None
    for w in words:
        word_mid = (w['top'] + w['bottom']) / 2
        if current_y is None:
            current_y, current_line = word_mid, [w]
        elif starts_new_transaction_row([w]) and current_line:
            lines.append(sorted(current_line, key=lambda x: x['x0']))
            current_line, current_y = [w], word_mid
        elif abs(word_mid - current_y) <= y_tolerance:
            current_line.append(w)
            current_y = sum((cw['top'] + cw['bottom']) / 2 for cw in current_line) / len(current_line)
        else:
            lines.append(sorted(current_line, key=lambda x: x['x0']))
            current_line, current_y = [w], word_mid
    if current_line:
        lines.append(sorted(current_line, key=lambda x: x['x0']))
    return lines


def parse_transaction_line(line_words: list[dict]) -> dict | None:
    if not line_words:
        return None
    first_word = line_words[0]['text']
    if not DATE_RE.match(first_word):
        return None

    date = first_word
    particulars_words, numbers = [], []

    for w in line_words[1:]:
        is_numeric = NUMBER_RE.match(w['text'].replace(',', ''))
        if w['x1'] > 360 and is_numeric:
            numbers.append((w['x1'], w['text']))
        else:
            particulars_words.append(w['text'])

    particulars = " ".join(particulars_words).strip()
    withdrawal, deposit, balance = "", "", ""

    if len(numbers) >= 1:
        balance = numbers[-1][1]
    if len(numbers) >= 2:
        x1, val = numbers[-2]
        if x1 < 440:
            withdrawal = val
        else:
            deposit = val
    if len(numbers) >= 3:
        x1, val = numbers[-3]
        if x1 < 440:
            withdrawal = val
        else:
            deposit = val

    return {"date": date, "particulars": particulars,
            "withdrawal": withdrawal, "deposit": deposit, "balance": balance}


def extract_account_info(first_page_text: str) -> dict:
    info = {}
    patterns = {
        "Statement Period": r'Between\s+(\d{2}-\d{2}-\d{4}\s+and\s+\d{2}-\d{2}-\d{4})',
        "Account Number":   r'account number\s+(\d+)',
        "Customer ID":      r'Customer ID\s+([A-Z0-9]+)',
        "CKYC ID":          r'CKYC ID\s+(\d+)',
        "Account Type":     r'A/c Type\s+(\w+)',
        "Mobile No":        r'Mobile No[.\s]+(\d+)',
        "Email (Customer)": r'E-Mail ID\s+([A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,})',
        "Branch Code":      r'Branch Code\s+(\d+)',
        "Branch Name":      r'Branch Name\s+([A-Z]+)',
        "IFSC Code":        r'IFSC Code\s+([A-Z0-9]+)',
        "MICR Code":        r'MICR Code\s+(\d+)',
    }
    for field, pattern in patterns.items():
        m = re.search(pattern, first_page_text, re.IGNORECASE)
        info[field] = m.group(1).strip() if m else ""

    # Name: ALL-CAPS lines immediately before the standalone "Name" label
    name_m = re.search(r'((?:[A-Z][A-Z\s&\./]+\n)+)Name\n', first_page_text)
    if name_m:
        lines = [l.strip() for l in name_m.group(1).strip().split('\n') if l.strip()]
        lines = [l for l in lines if l != info.get("Branch Name", "")]
        info["Account Name"] = " / ".join(lines)

    # Address: lines after the SECOND "Address\n" occurrence up to IFSC/MICR/A/c
    addr_blocks = list(re.finditer(r'Address\n', first_page_text))
    if len(addr_blocks) >= 2:
        start = addr_blocks[-1].end()
        end_m = re.search(r'IFSC Code|MICR Code|A/c Type', first_page_text[start:])
        addr_raw = first_page_text[start:start + end_m.start()] if end_m else first_page_text[start:start + 200]
        addr_lines = [l.strip() for l in addr_raw.split('\n') if l.strip()]
        info["Address"] = ", ".join(addr_lines)
    elif len(addr_blocks) == 1:
        start = addr_blocks[0].end()
        end_m = re.search(r'IFSC Code|MICR Code|A/c Type', first_page_text[start:])
        addr_raw = first_page_text[start:start + end_m.start()] if end_m else first_page_text[start:start + 200]
        addr_lines = [l.strip() for l in addr_raw.split('\n') if l.strip()]
        info["Address"] = ", ".join(addr_lines)

    return info


def extract_transactions(file_bytes: bytes) -> list[dict]:
    transactions = []
    with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
        for page in pdf.pages:
            lines = words_to_lines(page)
            for line_words in lines:
                line_text = " ".join(w['text'] for w in line_words)
                if is_disclaimer_text(line_text):
                    continue
                if 'Opening Balance' in line_text:
                    continue
                tx = parse_transaction_line(line_words)
                if tx:
                    transactions.append(tx)
                elif transactions and line_words and not starts_new_transaction_row(line_words):
                    continuation = [w['text'] for w in line_words if w['x0'] < 360 and not DATE_RE.match(w['text'])]
                    if continuation:
                        extra = " ".join(continuation).strip()
                        if extra and not is_disclaimer_text(extra):
                            if transactions[-1]['particulars']:
                                transactions[-1]['particulars'] += " " + extra
                            else:
                                transactions[-1]['particulars'] = extra
    return transactions


def extract_pdf_text(file_bytes: bytes) -> tuple[str, int]:
    page_texts = []
    with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
        total = len(pdf.pages)
        for i, page in enumerate(pdf.pages, 1):
            text = page.extract_text() or ""
            page_texts.append(f"--- Page {i} of {total} ---\n{text.strip()}")
    return "\n\n".join(page_texts).strip(), len(page_texts)


def build_excel_workbook(account_info: dict, transactions: list[dict]) -> openpyxl.Workbook:
    wb = openpyxl.Workbook()
    ws_info = wb.active
    ws_info.title = "Account Details"

    title_font  = Font(color="1E3A5F", bold=True, name="Calibri", size=14)
    label_font  = Font(bold=True, name="Calibri", size=11)
    value_font  = Font(name="Calibri", size=11)
    thin_border = Border(bottom=Side(style='thin', color='CBD5E1'))

    ws_info.merge_cells("A1:B1")
    c = ws_info["A1"]
    c.value = "UCO Bank — Account Statement Details"
    c.font  = title_font
    c.alignment = Alignment(horizontal="left", vertical="center")
    ws_info.row_dimensions[1].height = 30
    ws_info.column_dimensions["A"].width = 25
    ws_info.column_dimensions["B"].width = 45

    for r, (key, val) in enumerate(account_info.items(), start=2):
        lc = ws_info.cell(row=r, column=1, value=key)
        vc = ws_info.cell(row=r, column=2, value=val)
        lc.font, vc.font = label_font, value_font
        lc.border, vc.border = thin_border, thin_border
        if r % 2 == 0:
            fill = PatternFill(start_color="EBF8FF", end_color="EBF8FF", fill_type="solid")
            lc.fill, vc.fill = fill, fill

    ws_tx = wb.create_sheet(title="Transactions")
    headers    = ["Date", "Particulars", "Withdrawals (₹)", "Deposits (₹)", "Balance (₹)"]
    col_widths = [15, 55, 18, 18, 18]
    hdr_fill   = PatternFill(start_color="1E3A5F", end_color="1E3A5F", fill_type="solid")
    hdr_font   = Font(color="FFFFFF", bold=True, name="Calibri", size=11)
    debit_font = Font(name="Calibri", size=10, color="C53030")
    credit_font= Font(name="Calibri", size=10, color="276749")
    normal_font= Font(name="Calibri", size=10)

    for i, (h, w) in enumerate(zip(headers, col_widths), 1):
        c = ws_tx.cell(row=1, column=i, value=h)
        c.fill, c.font = hdr_fill, hdr_font
        c.alignment = Alignment(horizontal="center", vertical="center")
        ws_tx.column_dimensions[get_column_letter(i)].width = w
    ws_tx.row_dimensions[1].height = 22

    for r, tx in enumerate(transactions, 2):
        row_data = [tx.get("date",""), tx.get("particulars",""),
                    tx.get("withdrawal",""), tx.get("deposit",""), tx.get("balance","")]
        alt = PatternFill(start_color="F0F4F8", end_color="F0F4F8", fill_type="solid") if r % 2 == 0 else None
        for ci, val in enumerate(row_data, 1):
            cell = ws_tx.cell(row=r, column=ci, value=val)
            if alt:
                cell.fill = alt
            if ci == 3 and val:
                cell.font, cell.alignment = debit_font, Alignment(horizontal="right")
            elif ci == 4 and val:
                cell.font, cell.alignment = credit_font, Alignment(horizontal="right")
            elif ci == 5:
                cell.font  = Font(name="Calibri", size=10, bold=True)
                cell.alignment = Alignment(horizontal="right")
            else:
                cell.font = normal_font

    ws_tx.freeze_panes = "A2"
    return wb


# ─── Streamlit UI ─────────────────────────────────────────────────────────────

st.markdown("""
<div class="app-header">
  <div>
    <h1>🏦 Bank Statement → Excel</h1>
    <p>Deterministic extraction · Works offline · UCO Bank / multi-bank</p>
  </div>
</div>
""", unsafe_allow_html=True)

# ── Mode selector ─────────────────────────────────────────────────────────────
st.markdown("#### What do you want to do?")
mode = st.radio(
    label="mode",
    options=["📊 Parse & Download Excel", "🤖 Extract Text for AI"],
    horizontal=True,
    label_visibility="collapsed",
)
st.caption(
    "**Parse & Download Excel** — automatically extracts account details and all transactions into a styled Excel file."
    if mode == "📊 Parse & Download Excel"
    else "**Extract Text for AI** — pulls raw text from the PDF and builds a ready-to-paste prompt for ChatGPT, Claude, or Gemini."
)

st.divider()

# ── Upload ────────────────────────────────────────────────────────────────────
uploaded_file = st.file_uploader(
    "Upload your bank statement PDF",
    type=["pdf"],
    help="Supports text-based PDFs (UCO Bank, SBI, PNB, HDFC, ICICI etc.)"
)

if not uploaded_file:
    st.info("👆 Upload a bank statement PDF to get started.")
    st.stop()

submit = st.button("🚀 Process PDF", type="primary", use_container_width=False)

if not submit:
    st.stop()

file_bytes = uploaded_file.read()
# ══════════════════════════════════════════════════════════════════════════════
# MODE A — Parse & Download Excel
# ══════════════════════════════════════════════════════════════════════════════
if mode == "📊 Parse & Download Excel":

    with st.spinner("Extracting data…"):
        try:
            with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
                page1_text = pdf.pages[0].extract_text() or "" if pdf.pages else ""
            account_info  = extract_account_info(page1_text)
            transactions  = extract_transactions(file_bytes)
            pdf_text, page_count = extract_pdf_text(file_bytes)
        except Exception as e:
            st.error(f"Failed to read PDF: {e}")
            st.stop()

    if not transactions:
        st.error("No transactions found. Make sure the PDF contains selectable text (not a scanned image).")
        st.stop()

    # ── Stats row ─────────────────────────────────────────────────────────────
    total_withdrawals = sum(
        float(tx["withdrawal"].replace(",", "")) for tx in transactions if tx.get("withdrawal")
    )
    total_deposits = sum(
        float(tx["deposit"].replace(",", "")) for tx in transactions if tx.get("deposit")
    )

    st.markdown(f"""
    <div class="stat-row">
      <div class="stat-card">
        <div class="stat-label">Transactions</div>
        <div class="stat-value">{len(transactions)}</div>
        <div class="stat-sub">{page_count} pages processed</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Total Withdrawals</div>
        <div class="stat-value" style="color:#C53030">₹{total_withdrawals:,.2f}</div>
        <div class="stat-sub">Money out</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Total Deposits</div>
        <div class="stat-value" style="color:#276749">₹{total_deposits:,.2f}</div>
        <div class="stat-sub">Money in</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Closing Balance</div>
        <div class="stat-value">₹{transactions[-1].get("balance","—")}</div>
        <div class="stat-sub">{transactions[-1].get("date","")}</div>
      </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Download button ────────────────────────────────────────────────────────
    wb = build_excel_workbook(account_info, transactions)
    excel_buffer = io.BytesIO()
    wb.save(excel_buffer)
    excel_buffer.seek(0)

    col_dl, col_spacer = st.columns([2, 5])
    with col_dl:
        st.download_button(
            label="⬇️ Download Excel",
            data=excel_buffer,
            file_name=f"{uploaded_file.name.replace('.pdf', '')}_statement.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True,
            type="primary",
        )

    st.divider()

    # ── Tabs ───────────────────────────────────────────────────────────────────
    tab_info, tab_tx = st.tabs(["🏛️ Account Details", f"💳 Transactions ({len(transactions)})"])

    with tab_info:
        if not any(account_info.values()):
            st.warning("Could not extract account details from this PDF automatically.")
        else:
            for label, value in account_info.items():
                if value:
                    col_label, col_value = st.columns([1, 2])
                    with col_label:
                        st.markdown(f"**{label}**")
                    with col_value:
                        st.code(value, language=None)

    with tab_tx:
        import pandas as pd

        df = pd.DataFrame([{
            "Date":            tx.get("date", ""),
            "Particulars":     tx.get("particulars", ""),
            "Withdrawal (₹)":  tx.get("withdrawal", ""),
            "Deposit (₹)":     tx.get("deposit", ""),
            "Balance (₹)":     tx.get("balance", ""),
        } for tx in transactions])

        st.markdown(f"**{len(transactions)} transactions** extracted from {page_count} pages")
        st.dataframe(
            df,
            use_container_width=True,
            height=520,
            hide_index=True,
            column_config={
                "Date":           st.column_config.TextColumn("Date", width=110),
                "Particulars":    st.column_config.TextColumn("Particulars", width=380),
                "Withdrawal (₹)": st.column_config.TextColumn("Withdrawal (₹)", width=130),
                "Deposit (₹)":    st.column_config.TextColumn("Deposit (₹)", width=130),
                "Balance (₹)":    st.column_config.TextColumn("Balance (₹)", width=140),
            }
        )

        empty_particulars = sum(1 for tx in transactions if not tx.get("particulars"))
        if empty_particulars > 0:
            st.markdown(f'<div class="warn-pill">⚠️ {empty_particulars} rows have empty Particulars — check column alignment</div>', unsafe_allow_html=True)
        else:
            st.markdown('<div class="success-pill">✅ All rows have Particulars</div>', unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
# MODE B — Extract Text for AI
# ══════════════════════════════════════════════════════════════════════════════
else:
    with st.spinner("Extracting text from PDF…"):
        try:
            pdf_text, page_count = extract_pdf_text(file_bytes)
        except Exception as e:
            st.error(f"Failed to read PDF: {e}")
            st.stop()

    if not pdf_text.strip():
        st.error("No extractable text found. This PDF may be scanned/image-based.")
        st.stop()

    prompt = AI_EXCEL_PROMPT_TEMPLATE.format(pdf_text=pdf_text)

    # ── Stats ──────────────────────────────────────────────────────────────────
    st.markdown(f"""
    <div class="stat-row">
      <div class="stat-card">
        <div class="stat-label">Pages</div>
        <div class="stat-value">{page_count}</div>
        <div class="stat-sub">extracted</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Characters</div>
        <div class="stat-value">{len(pdf_text):,}</div>
        <div class="stat-sub">raw text</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Prompt Size</div>
        <div class="stat-value">{len(prompt):,}</div>
        <div class="stat-sub">chars ready to paste</div>
      </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Instructions ───────────────────────────────────────────────────────────
    st.info(
        "**How to use:** Download the prompt file below → open ChatGPT / Claude / Gemini "
        "→ paste the entire contents → the AI will return two CSV blocks (Account Details + Transactions) "
        "that you can copy into Excel."
    )

    # ── Download buttons ───────────────────────────────────────────────────────
    col1, col2, col3 = st.columns(3)

    with col1:
        st.download_button(
            label="⬇️ Download Full Prompt (.txt)",
            data=prompt,
            file_name=f"{uploaded_file.name.replace('.pdf', '')}_ai_prompt.txt",
            mime="text/plain",
            use_container_width=True,
            type="primary",
        )
    with col2:
        st.download_button(
            label="⬇️ Download Raw Text Only",
            data=pdf_text,
            file_name=f"{uploaded_file.name.replace('.pdf', '')}_extracted_text.txt",
            mime="text/plain",
            use_container_width=True,
        )

    st.divider()

    # ── Preview tabs ───────────────────────────────────────────────────────────
    tab_prompt_prev, tab_text_prev = st.tabs(["📋 Prompt Preview", "📄 Raw Text Preview"])

    with tab_prompt_prev:
        st.caption("First 3000 characters of the full prompt")
        st.code(
            prompt[:3000] + ("\n\n… (truncated — download for full prompt)" if len(prompt) > 3000 else ""),
            language=None
        )

    with tab_text_prev:
        st.caption(f"First 3000 characters of extracted text ({page_count} pages total)")
        st.code(
            pdf_text[:3000] + ("\n\n… (truncated)" if len(pdf_text) > 3000 else ""),
            language=None
        )