import io
import logging
import os
import re
from typing import Any, Dict, List

import dotenv
import openpyxl
import pdfplumber
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from pydantic import BaseModel

dotenv.load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(name)s - %(message)s")
logger = logging.getLogger("pdf_to_excel")

app = FastAPI(title="Bank Statement Extractor")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def select_extraction_mode(mode: str | None) -> str:
    """Always use deterministic parsing for this flow."""
    return "deterministic"


AI_EXCEL_PROMPT_TEMPLATE = """You are an expert bank statement data extraction assistant.

Create a clean Excel-ready output from the PDF text below.

Requirements:
- Preserve every transaction row in the statement.
- Create two sheets: Account Details and Transactions.
- Account Details columns: Field, Value.
- Transactions columns: Date, Particulars, Withdrawal, Deposit, Balance.
- Keep amounts exactly as written unless a clear formatting cleanup is needed.
- Put withdrawals and deposits in separate columns. Leave missing values blank.
- If a transaction description wraps across lines, merge it into the same row.
- Ignore page headers, footers, disclaimers, duplicate column headings, and summary noise.
- Return the result as CSV blocks, one block per sheet, so I can paste/import it into Excel.
- If anything is uncertain, add a short Notes section after the CSV blocks.

PDF text:
{pdf_text}
"""


def extract_pdf_text(file_bytes: bytes) -> tuple[str, int]:
    """Extract plain text from every page of a PDF, preserving page boundaries."""
    page_texts = []
    with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
        total_pages = len(pdf.pages)
        for page_idx, page in enumerate(pdf.pages, start=1):
            text = page.extract_text() or ""
            page_texts.append(f"--- Page {page_idx} of {total_pages} ---\n{text.strip()}")

    full_text = "\n\n".join(page_texts).strip()
    return full_text, len(page_texts)


def build_ai_excel_prompt(pdf_text: str) -> str:
    """Build the copy-ready prompt users can paste into ChatGPT or another AI."""
    return AI_EXCEL_PROMPT_TEMPLATE.format(pdf_text=pdf_text.strip())


def extract_account_info(first_page_text: str) -> dict:
    """Parse the account details block from page 1."""
    info = {}
    patterns = {
        "Statement Period": r'Between\s+(\d{2}-\d{2}-\d{4}\s+and\s+\d{2}-\d{2}-\d{4})',
        "Account Number": r'account number\s+(\d+)',
        "Customer ID": r'Customer ID\s+([A-Z0-9]+)',
        "CKYC ID": r'CKYC ID\s+(\d+)',
        "Account Type": r'A/c Type\s+(\w+)',
        "Mobile No": r'Mobile No[.\s]+(\d+)',
        "Email ID": r'E-Mail ID\s+([^\n]+@[^\n]+)',
        "Branch Code": r'Branch Code\s+(\d+)',
        "Branch Name": r'Branch Name\s+([A-Z]+)',
        "IFSC Code": r'IFSC Code\s+([A-Z0-9]+)',
        "MICR Code": r'MICR Code\s+(\d+)',
    }

    for field, pattern in patterns.items():
        m = re.search(pattern, first_page_text, re.IGNORECASE)
        info[field] = m.group(1).strip() if m else ""

    name_match = re.search(r'Name\s*\n(.*?)\n.*?Address', first_page_text, re.DOTALL)
    if name_match:
        name_lines = name_match.group(1).strip().split('\n')
        info["Account Name"] = " ".join(l.strip() for l in name_lines if l.strip())
    else:
        m = re.search(r'Name\s+([A-Z\s]+(?:\n[A-Z\s]+)?)', first_page_text)
        info["Account Name"] = m.group(1).strip().replace('\n', ' ') if m else ""

    addr_match = re.search(r'Address\s*\n(.*?)(?=A/c Type|Branch Code|IFSC)', first_page_text, re.DOTALL)
    if addr_match:
        addr_lines = [l.strip() for l in addr_match.group(1).split('\n') if l.strip()]
        info["Address"] = ", ".join(addr_lines)

    return info


DATE_RE = re.compile(r'^(\d{2}-(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-\d{4})', re.IGNORECASE)
NUMBER_RE = re.compile(r'^[\d,]+(?:\.\d+)?$')


def is_disclaimer_text(text: str) -> bool:
    if not text:
        return False

    normalized = re.sub(r'\s+', ' ', text).strip().lower()
    if not normalized:
        return False

    disclaimer_markers = [
        'this is an auto generated e-statement',
        'this is auto generated',
        'for any query',
        'if you need any clarification',
        'please contact your branch',
        'please contact the branch',
        'generated by',
        'statement generated',
        'disclaimer',
    ]
    return any(marker in normalized for marker in disclaimer_markers)


def starts_new_transaction_row(line_words: list[dict]) -> bool:
    if not line_words:
        return False

    first_text = line_words[0].get('text', '').strip()
    return bool(DATE_RE.match(first_text))


def words_to_lines(page, y_tolerance=6) -> list[list[dict]]:
    words = page.extract_words(x_tolerance=4, y_tolerance=4)
    if not words:
        return []

    words.sort(key=lambda w: (w['top'] + w['bottom']) / 2)
    lines = []
    current_line = []
    current_y = None

    for w in words:
        word_mid = (w['top'] + w['bottom']) / 2
        text = w.get('text', '').strip()

        if current_y is None:
            current_y = word_mid
            current_line.append(w)
        elif starts_new_transaction_row([w]) and current_line:
            lines.append(sorted(current_line, key=lambda x: x['x0']))
            current_line = [w]
            current_y = word_mid
        elif abs(word_mid - current_y) <= y_tolerance:
            current_line.append(w)
            current_y = sum((cw['top'] + cw['bottom']) / 2 for cw in current_line) / len(current_line)
        else:
            lines.append(sorted(current_line, key=lambda x: x['x0']))
            current_line = [w]
            current_y = word_mid

    if current_line:
        lines.append(sorted(current_line, key=lambda x: x['x0']))

    return lines


def parse_transaction_line(line_words: list[dict]) -> dict | None:
    if not line_words:
        return None

    first_word = line_words[0]['text']
    if not DATE_RE.match(first_word):
        return None

    date = first_word
    particulars_words = []
    numbers = []

    for w in line_words[1:]:
        is_numeric = NUMBER_RE.match(w['text'].replace(',', ''))
        if w['x1'] > 360 and is_numeric:
            numbers.append((w['x1'], w['text']))
        else:
            particulars_words.append(w['text'])

    particulars = " ".join(particulars_words).strip()
    withdrawal = ""
    deposit = ""
    balance = ""

    if len(numbers) >= 1:
        balance = numbers[-1][1]

    if len(numbers) >= 2:
        x1, val = numbers[-2]
        if x1 < 440:
            withdrawal = val
        else:
            deposit = val

    if len(numbers) >= 3:
        x1, val = numbers[-3]
        if x1 < 440:
            withdrawal = val
        else:
            deposit = val

    return {
        "date": date,
        "particulars": particulars,
        "withdrawal": withdrawal,
        "deposit": deposit,
        "balance": balance,
    }


def extract_transactions(file_bytes: bytes) -> list[dict]:
    transactions = []
    opening_balance = None

    with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
        for page in pdf.pages:
            lines = words_to_lines(page)
            for line_words in lines:
                line_text = " ".join(w['text'] for w in line_words)

                if is_disclaimer_text(line_text):
                    continue

                if 'Opening Balance' in line_text:
                    nums = [w['text'] for w in line_words if NUMBER_RE.match(w['text'].replace(',', ''))]
                    if nums:
                        opening_balance = nums[-1]
                    continue

                tx = parse_transaction_line(line_words)
                if tx:
                    transactions.append(tx)
                elif transactions and line_words and not starts_new_transaction_row(line_words):
                    continuation_words = []
                    for w in line_words:
                        if w['x0'] < 360 and not DATE_RE.match(w['text']):
                            continuation_words.append(w['text'])

                    if continuation_words:
                        extra_text = " ".join(continuation_words).strip()
                        if extra_text and not is_disclaimer_text(extra_text):
                            if transactions[-1]['particulars']:
                                transactions[-1]['particulars'] += " " + extra_text
                            else:
                                transactions[-1]['particulars'] = extra_text

    if opening_balance and transactions:
        transactions[0]['opening_balance'] = opening_balance

    return transactions


class ExportPayload(BaseModel):
    account_info: Dict[str, Any]
    transactions: List[Dict[str, Any]]


def build_excel_workbook(account_info: Dict[str, Any], transactions: List[Dict[str, Any]]) -> openpyxl.Workbook:
    wb = openpyxl.Workbook()

    ws_info = wb.active
    ws_info.title = "Account Details"

    title_font = Font(color="1E3A5F", bold=True, name="Calibri", size=14)
    label_font = Font(bold=True, name="Calibri", size=11)
    value_font = Font(name="Calibri", size=11)
    thin_border = Border(bottom=Side(style='thin', color='CBD5E1'))

    ws_info.merge_cells("A1:B1")
    title_cell = ws_info["A1"]
    title_cell.value = "UCO Bank — Account Statement Details"
    title_cell.font = title_font
    title_cell.alignment = Alignment(horizontal="left", vertical="center")
    ws_info.row_dimensions[1].height = 30
    ws_info.column_dimensions["A"].width = 25
    ws_info.column_dimensions["B"].width = 45

    for row_idx, (key, val) in enumerate(account_info.items(), start=2):
        label_cell = ws_info.cell(row=row_idx, column=1, value=key)
        value_cell = ws_info.cell(row=row_idx, column=2, value=val)
        label_cell.font = label_font
        value_cell.font = value_font
        label_cell.border = thin_border
        value_cell.border = thin_border
        if row_idx % 2 == 0:
            for cell in [label_cell, value_cell]:
                cell.fill = PatternFill(start_color="EBF8FF", end_color="EBF8FF", fill_type="solid")

    ws_tx = wb.create_sheet(title="Transactions")
    headers = ["Date", "Particulars", "Withdrawals (₹)", "Deposits (₹)", "Balance (₹)"]
    header_fill = PatternFill(start_color="1E3A5F", end_color="1E3A5F", fill_type="solid")
    header_font = Font(color="FFFFFF", bold=True, name="Calibri", size=11)
    debit_font = Font(name="Calibri", size=10, color="C53030")
    credit_font = Font(name="Calibri", size=10, color="276749")
    normal_font = Font(name="Calibri", size=10)

    col_widths = [15, 55, 18, 18, 18]
    for i, (h, w) in enumerate(zip(headers, col_widths), start=1):
        cell = ws_tx.cell(row=1, column=i, value=h)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")
        ws_tx.column_dimensions[get_column_letter(i)].width = w
    ws_tx.row_dimensions[1].height = 22

    for row_idx, tx in enumerate(transactions, start=2):
        row_data = [tx.get("date", ""), tx.get("particulars", ""), tx.get("withdrawal", ""), tx.get("deposit", ""), tx.get("balance", "")]
        alt_fill = PatternFill(start_color="F0F4F8", end_color="F0F4F8", fill_type="solid") if row_idx % 2 == 0 else None

        for col_idx, value in enumerate(row_data, start=1):
            cell = ws_tx.cell(row=row_idx, column=col_idx, value=value)
            if alt_fill:
                cell.fill = alt_fill

            if col_idx == 3 and value:
                cell.font = debit_font
                cell.alignment = Alignment(horizontal="right")
            elif col_idx == 4 and value:
                cell.font = credit_font
                cell.alignment = Alignment(horizontal="right")
            elif col_idx == 5:
                cell.font = Font(name="Calibri", size=10, bold=True)
                cell.alignment = Alignment(horizontal="right")
            else:
                cell.font = normal_font

    ws_tx.freeze_panes = "A2"
    return wb


@app.post("/upload")
async def upload_pdf(file: UploadFile = File(...), extraction_mode: str | None = Form(None)):
    logger.info("Received request to /upload. Filename: '%s', Content-type: '%s'", file.filename, file.content_type)
    if not file.filename or not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are accepted.")

    file_bytes = await file.read()
    mode = select_extraction_mode(extraction_mode)
    logger.info("Selected extraction mode: %s", mode)

    try:
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            page1_text = pdf.pages[0].extract_text() or "" if pdf.pages else ""
    except Exception as exc:
        logger.exception("Failed to extract account info from first page: %s", str(exc))
        page1_text = ""

    account_info = extract_account_info(page1_text)
    transactions = extract_transactions(file_bytes)

    if not transactions:
        raise HTTPException(status_code=422, detail="No transactions found in this PDF.")

    return {
        "account_info": account_info,
        "transactions": transactions,
        "total_rows": len(transactions),
    }


@app.post("/upload-excel")
async def upload_pdf_and_export_excel(file: UploadFile = File(...)):
    logger.info("Received request to /upload-excel. Filename: '%s'", file.filename)
    if not file.filename or not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are accepted.")

    file_bytes = await file.read()

    try:
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            page1_text = pdf.pages[0].extract_text() or "" if pdf.pages else ""
    except Exception as exc:
        logger.exception("Failed to read PDF for Excel export: %s", str(exc))
        page1_text = ""

    account_info = extract_account_info(page1_text)
    transactions = extract_transactions(file_bytes)
    if not transactions:
        raise HTTPException(status_code=422, detail="No transactions found in this PDF.")

    workbook = build_excel_workbook(account_info, transactions)
    output = io.BytesIO()
    workbook.save(output)
    output.seek(0)

    filename = f"{os.path.splitext(file.filename)[0]}_statement.xlsx"
    return StreamingResponse(
        output,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


@app.post("/extract-text")
async def extract_text_for_ai(file: UploadFile = File(...)):
    logger.info("Received request to /extract-text. Filename: '%s'", file.filename)
    if not file.filename or not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are accepted.")

    file_bytes = await file.read()
    extracted_text, page_count = extract_pdf_text(file_bytes)
    if not extracted_text:
        raise HTTPException(status_code=422, detail="No extractable text found in this PDF.")

    prompt = build_ai_excel_prompt(extracted_text)
    return {
        "filename": file.filename,
        "page_count": page_count,
        "text": extracted_text,
        "prompt": prompt,
        "text_characters": len(extracted_text),
        "prompt_characters": len(prompt),
    }


@app.post("/export")
async def export_excel(payload: ExportPayload):
    workbook = build_excel_workbook(payload.account_info, payload.transactions)
    output = io.BytesIO()
    workbook.save(output)
    output.seek(0)
    return StreamingResponse(
        output,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": "attachment; filename=bank_statement.xlsx"},
    )


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
